name: Build
on: [push]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3

      - name: Build library
        uses: Rockman18/ghactions-mplabx@master
        with:
          project: cutcutgo.X
          configuration: cutcutgo
      
      - name: Upload firmware binaries
        uses: actions/upload-artifact@v3
        with:
          name: cricut_maker1_cutcutgo_cfw.hex
          path: cutcutgo.X/dist/cutcutgo/production/cutcutgo.X.production.hex
          if-no-files-found: error


