name: sphinx
on:
  push:
    paths:
      - 'docs/**'

permissions:
  contents: write

env:
  DEFAULT_BRANCH: "main"

jobs:

  build-and-deploy:
    name: Build and deploy to Github pages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
    
      - name: Install dependencies
        run: pip install -r ./docs/requirements.txt

      - name: Build sphinx docs
        run: sphinx-build ./docs/source ./docs/build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html/
